/*
 * frmain.c
 * Since the main.c is auto-generated by STM32CubeIDE
 * this is the real "main" file for the FreeRTOS version
 * of this project.
 *
 *  Created on: 2025-04-22
 *  Updated on: 2025-04-25
 *      Author: Douglas P. Fields, Jr.
 *   Copyright: 2025, Douglas P. Fields, Jr.
 *     License: Apache 2.0
 */

#include <stdio.h>

#include "main.h"
#include "realmain.h"
#include "frmain.h"

// FreeRTOS includes
#include "FreeRTOS.h"
#include "task.h"


/** A FreeRTOS task that just blinks the green LED */
void blink_green(void *param) {
  while (1) {
    HAL_GPIO_TogglePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin);
    vTaskDelay(100);
  }
}

/** A FreeRTOS task that just blinks the red LED */
void blink_red(void *param) {
  while (1) {
    HAL_GPIO_TogglePin(LED_RED_GPIO_Port, LED_RED_Pin);
    vTaskDelay(750);
  }
}

void task_check_serial_io(void *param) {
  while (1) {
    check_io();
    vTaskDelay(1);
  }
}

void task_send_serial_data(void *param) {
  char msg[] = "Hello, world!\r\n\r\n";

  while (1) {
    serial_transmit((uint8_t *)msg, sizeof(msg));
    vTaskDelay(997);
  }
}

void task_read_serial_data(void *param) {
  char msg[50];
  uint16_t c;
  int len;

  while (1) {
    c = serial_read();

    // No character waiting for input
    if (c >= 0x100) {
      vTaskDelay(1);
      continue;
    }

    len = snprintf(msg, sizeof(msg), "You typed: %02X\r\n\r\n", (int)c);
    serial_transmit((uint8_t *)msg, len);
  }
}


void frmain() {
  TaskHandle_t blink_green_task;
  TaskHandle_t blink_red_task;
  TaskHandle_t check_serial_io;
  TaskHandle_t send_serial_data;
  TaskHandle_t read_serial_data;

  BaseType_t status;

  //////////////////////////////////////////////////////////////////
  // UART handler initialization

  init_usart_dma_io();

  // Start our USART receiving and error interrupts
  // TODO: This probably is not necessary anymore
  LL_USART_EnableIT_RXNE(MIDI1_UART);
  LL_USART_EnableIT_RXNE(CONSOLE_UART);
  LL_USART_EnableIT_ERROR(MIDI1_UART);
  LL_USART_EnableIT_ERROR(CONSOLE_UART);


  //////////////////////////////////////////////////////////////////
  // Debugger Initialization

  // Enable Segger SystemView
  traceSTART();

  //////////////////////////////////////////////////////////////////
  // Initial tasks

  // Create a test task that blinks a different LED than LD1
  status = xTaskCreate(blink_green, "Bl-Grn", 200, NULL, 5, &blink_green_task);
  configASSERT(status == pdPASS);

  status = xTaskCreate(blink_red, "Bl-Red", 200, NULL, 5, &blink_red_task);
  configASSERT(status == pdPASS);

  // Serial testing tasks
  status = xTaskCreate(task_check_serial_io, "UART-IO", 200, NULL, 2, &check_serial_io);
  configASSERT(status == pdPASS);

  status = xTaskCreate(task_send_serial_data, "UART-Send", 200, NULL, 8, &send_serial_data);
  configASSERT(status == pdPASS);

  status = xTaskCreate(task_read_serial_data, "UART-Read", 200, NULL, 3, &read_serial_data);
  configASSERT(status == pdPASS);

  //////////////////////////////////////////////////////////////////
  // Start FreeRTOS

  // This should never return unless there is a problem
  vTaskStartScheduler();

  // If there's a problem, blink the Blue LED
  while (1) {
    HAL_GPIO_TogglePin(LED_BLUE_GPIO_Port, LED_BLUE_Pin);
    HAL_Delay(500);
  }
}
