/*
 * frmain.c
 * Since the main.c is auto-generated by STM32CubeIDE
 * this is the real "main" file for the FreeRTOS version
 * of this project.
 *
 *  Created on: 2025-04-22
 *  Updated on: 2025-04-22
 *      Author: Douglas P. Fields, Jr.
 *   Copyright: 2025, Douglas P. Fields, Jr.
 *     License: Apache 2.0
 */


#include "main.h"

// FreeRTOS includes
#include "FreeRTOS.h"
#include "task.h"


/** A FreeRTOS task that just blinks the green LED */
void blink_green(void *param) {
  while (1) {
    HAL_GPIO_TogglePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin);
    vTaskDelay(100);
  }
}

/** A FreeRTOS task that just blinks the red LED */
void blink_red(void *param) {
  while (1) {
    HAL_GPIO_TogglePin(LED_RED_GPIO_Port, LED_RED_Pin);
    vTaskDelay(750);
  }
}


void frmain() {
  TaskHandle_t blink_green_task;
  TaskHandle_t blink_red_task;

  BaseType_t status;

  // Enable Segger SystemView
  traceSTART();

  // Create a test task that blinks a different LED than LD1
  status = xTaskCreate(blink_green, "Bl-Grn", 200, NULL, 2, &blink_green_task);
  configASSERT(status == pdPASS);

  status = xTaskCreate(blink_red, "Bl-Red", 200, NULL, 2, &blink_red_task);
  configASSERT(status == pdPASS);

  // Start FreeRTOS
  // This should never return unless there is a problem
  vTaskStartScheduler();

  // If there's a problem, blink the Blue LED
  while (1) {
    HAL_GPIO_TogglePin(LED_BLUE_GPIO_Port, LED_BLUE_Pin);
    HAL_Delay(500);
  }
}
