/*
 * usbmain.c
 * Since the main.c is auto-generated by STM32CubeIDE
 * this is the real "main" file for the USB testing
 * of this project.
 *
 *  Created on: 2025-04-27
 *  Updated on: 2025-04-27
 *      Author: Douglas P. Fields, Jr.
 *   Copyright: 2025, Douglas P. Fields, Jr.
 *     License: Apache 2.0
 *
 * Useful reference:
 * https://www.instructables.com/STM32-As-HID-USB-Keyboard-STM32-Tutorials/
 */

#include <stdio.h>

#include "main.h"
#include "realmain.h"
#include "usbmain.h"

#include "usbd_hid.h"


extern USBD_HandleTypeDef hUsbDeviceFS;

typedef struct {
  uint8_t MODIFIER;
  uint8_t RESERVED;
  uint8_t KEYCODE1;
  uint8_t KEYCODE2;
  uint8_t KEYCODE3;
  uint8_t KEYCODE4;
  uint8_t KEYCODE5;
  uint8_t KEYCODE6;
} subKeyBoard;

subKeyBoard keyBoardHIDsub = {0,0,0,0,0,0,0,0};


void usbmain() {
  // If there's a problem, blink the Blue LED
  while (1) {
    keyBoardHIDsub.MODIFIER=0x02;  // To press shift key
    keyBoardHIDsub.KEYCODE1=0x04;  // Press A key
    // keyBoardHIDsub.KEYCODE2=0x05;  // Press B key
    // keyBoardHIDsub.KEYCODE3=0x06;  // Press C key
    USBD_HID_SendReport(&hUsbDeviceFS, (uint8_t *)&keyBoardHIDsub, sizeof(keyBoardHIDsub));
    HAL_Delay(50);
    keyBoardHIDsub.MODIFIER=0x00;  // To release shift key
    keyBoardHIDsub.KEYCODE1=0x00;  // Release A key
    // keyBoardHIDsub.KEYCODE2=0x00;  // Release B key
    // keyBoardHIDsub.KEYCODE3=0x00;  // Release C key
    USBD_HID_SendReport(&hUsbDeviceFS, (uint8_t *)&keyBoardHIDsub, sizeof(keyBoardHIDsub));
    HAL_Delay(5000);
  }
}
